"""voice_memory table

Revision ID: 18700f72def5
Revises: 89dc9ae54b7e
Create Date: 2026-06-04 00:09:19.880149
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "18700f72def5"
down_revision: str | None = "89dc9ae54b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_memory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slack_user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("x", "linkedin", name="draftplatform", native_enum=False),
            nullable=False,
        ),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), server_default="edit", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voice_memory")
    # ### end Alembic commands ###
