"""phase3_draft_tables

Revision ID: 358179d1d889
Revises:
Create Date: 2026-06-02 22:42:25.876213
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "358179d1d889"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "draft_batch",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slack_channel_id", sa.String(length=64), nullable=False),
        sa.Column("slack_user_id", sa.String(length=64), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("slack_message_ts", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "approved", "cancelled", "expired", name="batchstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "draft",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "regenerating",
                "cancelled",
                name="draftstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["draft_batch.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "slot_index", name="uq_draft_batch_slot"),
    )
    op.create_table(
        "approval_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("approve", "regenerate", "cancel", name="approvalaction", native_enum=False),
            nullable=False,
        ),
        sa.Column("slack_user_id", sa.String(length=64), nullable=False),
        sa.Column("publish_url", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["draft_batch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["draft_id"], ["draft.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("approval_event")
    op.drop_table("draft")
    op.drop_table("draft_batch")
    # ### end Alembic commands ###
