"""voice_profile

Revision ID: 83e43d7f682c
Revises: b20b1793fec2
Create Date: 2026-06-03 16:41:01.873591
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "83e43d7f682c"
down_revision: str | None = "b20b1793fec2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slack_user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("x", "linkedin", name="draftplatform", native_enum=False),
            nullable=False,
        ),
        sa.Column("sample_posts", sa.JSON(), nullable=False),
        sa.Column("voice_card", sa.Text(), nullable=False),
        sa.Column("positioning", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slack_user_id", "platform", name="uq_voice_user_platform"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voice_profile")
    # ### end Alembic commands ###
