"""draft_batch candidate_ideas + chosen_idea_index

Revision ID: 89dc9ae54b7e
Revises: 83e43d7f682c
Create Date: 2026-06-03 17:51:18.686231
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89dc9ae54b7e"
down_revision: str | None = "83e43d7f682c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "draft_batch", sa.Column("candidate_ideas", sa.JSON(), server_default="[]", nullable=False)
    )
    op.add_column("draft_batch", sa.Column("chosen_idea_index", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("draft_batch", "chosen_idea_index")
    op.drop_column("draft_batch", "candidate_ideas")
    # ### end Alembic commands ###
