"""draft_platform

Revision ID: b20b1793fec2
Revises: 358179d1d889
Create Date: 2026-06-03 11:41:14.378449
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b20b1793fec2"
down_revision: str | None = "358179d1d889"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "draft",
        sa.Column(
            "platform",
            sa.Enum("x", "linkedin", name="draftplatform", native_enum=False),
            server_default="x",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("draft", "platform")
    # ### end Alembic commands ###
